#!/bin/bash
#
#curl http://localhost:5000/order/ndvi.
#curl http://localhost:5000/order/ndvi..
#curl http://localhost:5000/order/ndvi...
#curl http://localhost:5000/order/ndvi....
#curl http://localhost:5000/order/ndvi.....
#curl http://localhost:5000/order/ndvi......
#curl http://localhost:5000/order/ndvi.......
#curl http://localhost:5000/order/ndvi........
#curl http://localhost:5000/order/ndvi.........
#curl http://localhost:5000/order/ndvi..........
